name: Preprod CI

on:
  push:
    branches: [ "qa-release-V1.0.0" ]
  workflow_dispatch:
  

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'sbt'
    - name: compile code
      run: sbt dist
    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.4
      env:
        HOST: ${{ secrets.PREPROD_HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.PREPROD_SSH }}
      with:
        source: "target/universal/gdsservice-1.0-SNAPSHOT.zip"
        target: "deployments"
        strip_components: 2
    - name: Install Dependencies
      uses: appleboy/ssh-action@v0.1.10
      with:
          host: ${{ secrets.PREPROD_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PREPROD_SSH }}
          script_stop: true
          script: |
            sudo systemctl stop gdsapp.service
            ~/deployments/scripts/gdsdeploy.sh
            ls -al
            sudo systemctl start gdsapp.service
